input_dir: "demo/"
output_dir: "demo/output/"
analysis_name: "actin"

foldseek_databases:
- "afdb50"
- "afdb-swissprot"
- "afdb-proteome"
plotting_modes:
- "pca_tsne"
- "pca_umap"

max_blast_hits: 3000
max_foldseek_hits: 3000
max_structures: 5000

taxon_focus: 'euk'

uniprot_additional_fields: []
min_length: 0
max_length: 0

# Resource execution settings
resources:
    mem_mb: 16 * 1000
cores: 8
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 10
